modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="trialmod"
version="1.0"
displayName="TrialMod"
authors="Lotus Team"
description='''
a simple mod
'''

[[dependencies.trialmod]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.trialmod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,)"
ordering="NONE"
side="BOTH"